### PR TITLE
Notofication

### PR DESCRIPTION
**Pull request by hola-ale**
Hi, I did our first notification system. It's very simple and not perfect, but the general idea is that the bell icon appears near the avatar on the card when sb receives a new request or his/ her request has been accepted  by someone.
The placement of the icons has to be improved
Screenshot 2021-05-03 at 22 32 05
Screenshot 2021-05-03 at 22 36 32

### CODE REVIEW

**Comment by Alexboedtker** [comment]
Looks good! So the bell appears on anything that is new as well correct? that is how the user knows what is new vs not?

**Comment by hola-ale** [comment]
The bells appears on those two types of new activities on user's account *new request waiting for the user to act or the accepted swap) and won't disappear until the user display the details of request or the new swap

**Comment by hola-ale** [comment]
Screenshot 2021-05-04 at 11 28 58

**Comment by Alexboedtker** [comment]
LGTM

**Comment by SzczesnaAg** [comment]
lgtm

**Pull request merged**
